name: Release Hero on S3

permissions:
  contents: write


on:
  push:
    branches: ["development"]   
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            short-name: linux-i64
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-latest
          #   short-name: linux-arm64            
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          #   short-name: macos-i64
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          #   short-name: macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref_name }} and your repository is ${{ github.repository }}."
      
      # - name: Install dependencies
      #   run: |
      #     if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
      #       set -x
      #       sudo apt update
      #       sudo apt install -y libgc-dev tmux git rsync curl imagemagick redis gcc
      #       redis-server --daemonize yes
      #       sudo apt install -y build-essential wget autoconf libtool         
      #     else
      #       brew install libgc tmux git rsync curl redis libpq
      #       brew services start redis
      #     fi          
      #     sleep 2
      #     redis-cli ping

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: INSTALLBASE
        run: |
          cd $(pwd) && sudo bash +x scripts/githubactions.sh

      # - name: Get crystalweb
      #   run: |
      #     mkdir -p ~/.vmodules
      #     cd $(pwd)
      #     cd ..
      #     find . -maxdepth 2
      #     git clone --depth 1 https://github.com/freeflowuniverse/webcomponents


      # - name: DEBUG
      #   run: |
      #     set +x
      #     cd $(pwd)
      #     cd ..
      #     echo "******** LS BASE CODE"
      #     find . -maxdepth 2
      #     echo "******** LS CRYSTALLIB"
      #     cd $(pwd)
      #     find . -maxdepth 2
      #     git status
      #     echo "******** LS WEBCOMPONENTS"
      #     cd $(pwd)
      #     cd ..
      #     cd webcomponents  
      #     find . -maxdepth 2
      #     git status
      #     echo "******** END"

      # - name: Get crystallib
      #   run: |
      #     set +x
      #     mkdir -p ~/.vmodules/freeflowuniverse
      #     rm -f ~/.vmodules/freeflowuniverse/crystallib
      #     ln -s $(pwd)/crystallib ~/.vmodules/freeflowuniverse/crystallib
      #     rm -f ~/.vmodules/freeflowuniverse/webcomponents
      #     cd $(pwd)
      #     cd ..                    
      #     find . -maxdepth 2
      #     ln -s $(pwd)/../webcomponents/webcomponents ~/.vmodules/freeflowuniverse/webcomponents
      #     ls ~/.vmodules
      #     ls ~/.vmodules/freeflowuniverse
      #     ls ~/.vmodules/freeflowuniverse/crystallib
      #     ls ~/.vmodules/freeflowuniverse/webcomponents

      # - name: Setup Vlang
      #   uses: vlang/setup-v@v1.3
      #   with:
      #     check-latest: true

      # - name: Install secp256k1
      #   run: |
      #     if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
      #       set -x
      #       cd /tmp
      #       wget https://github.com/bitcoin-core/secp256k1/archive/refs/tags/v0.3.2.tar.gz
      #       tar -xvf v0.3.2.tar.gz
      #       cd secp256k1-0.3.2/
      #       ./autogen.sh
      #       ./configure
      #       sudo make -j 5
      #       sudo make install            
      #     else
      #       echo "no secp256k1 install"
      #     fi

      # - name: Build hero
      #   run: |
      #     set -x
      #     pushd cli/hero
      #     uname -m
      #     if [[ "$OSTYPE" == "darwin"* ]]; then
      #     v -enable-globals -w -cg hero.v
      #     else
      #     # -prod
      #     v -enable-globals -w -cg -cflags -static -cc gcc hero.v
      #     fi
      #     chmod +x hero
      #     mkdir -p ~/upload
      #     mv hero ~/upload/hero-${{ matrix.short-name }}
      #     find ~/upload
      #     popd

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
